name: pearl
channels:
  - conda-forge
  - pytorch
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.9
  - pytorch
  - scipy
  - matplotlib
  - seaborn
  - fenics=2019.1.0
  - dolfin-adjoint=2019.1.0
  - gymnasium
  - pyyaml
  - wandb
  - tqdm
  - imageio
  - ipykernel