
# Global settings
global: 
  exp_name: "pearl_leaderfollower_meanfield"
  device: "cpu"

# Environment settings
env:
  env_type: "leaderfollower_meanfield"
  env_params: # See envs constructor for envs specific parameters
    random_init: True
    random_target: True
    T: 20.0
    dt: 0.2
    beta: 0.1
    beta_g: 0.1
    save_plots: False
    save_gifs: False

# Logger settings
logger:
  logger_type: "wandb"
  track: False
  mode: "online"
  logger_params:
    project_name: "leaderfollower_meanfield"

# Agent settings
agent:
  agent_type: "pearl_agent"
  agent_params:
    actor:
      state_units: [1024, 1024]
      param_units: [1024, 1024]
      head_units: [1024, 1024]
      activation: tanh
      actor_logstd_init: -1.0
    adjoint_net:
      state_units: [1024, 1024]
      param_units: [1024, 1024]
      head_units: [1024, 1024]
      activation: tanh
    parametric: True 
    deterministic: True
    last_activation: False

# Trainer settings
trainer:
  trainer_type: "pearl_trainer"
  trainer_params:
    max_steps: 100000
    actor_learning_rate: 0.00001
    adjoint_net_learning_rate: 0.00001
    adam_betas: [0.9, 0.999]
    adam_eps: 1e-08
    target_adjoint_net_alpha: 0.995
    adjoint_net_iterations: 32
    grad_clip: False
    max_grad_norm: 1.0
    short_horizon: 16
    adjoint_net_lambda: 0.95
    gamma: 0.99
    evaluations: 10
    save_model: False
    save_intervals: 1000
    plot_intervals: 1000


